#!/bin/bash
#
# Gather info from tacacs logs
#
# Start

source=/var/log/tac_plus.log
tmp=/tmp/tacacs-audit-tmp
format=/usr/local/bin/tacacs-audit-awk

egrep 'login query' $source | awk '{print $1,$2,$3,$4,$5,$10,$13}' | sed "s/'//g" >> $tmp

$format $tmp
rm $tmp

# End
